# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-08 11:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20180108_1932'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': '教程', 'verbose_name_plural': '教程0'},
        ),
    ]
